### ISSUE TITLE
如何开始训练

### ISSUE THREAD

**Issue by jack121388** [mrcchenfeng/gobang#1]
我开始训练就说找不到模型，使用初始模型，然后就不动了。我个人有一块4090.想要尝试做一下这个，可以加一个您的微信吗

**Comment by CloudSwordSage** [comment]
呃，然后整个项目我训练失败，想着等后续学习后再完善
目前我3000轮次的训练没有任何收敛，如果想自己尝试的话，运行collect.py，可以多开几个用于并行收集，然后运行train.py，这个只运行一个就行，多多少少有些bug，需要自己修一下

**Comment by CloudSwordSage** [comment]
现在可以直接运行 train 进行训练了，目前也可以通过 web.py 游玩，不过模型还没跑好，它很菜，运行完 web.p y后去访问本机的 8080 端口即可，在训练时通过 -cn 指定数据收集的进程数，默认 4 进程，config.py 里设置训练时会用到的参数，web.py 游玩时可以试着将 playout 设置高点，训练时也是，蒙特卡洛树搜索的模拟次数越高效果越好
